Try to confirm deployment

diff --git a/.github/workflows/shared.twitposter.deploy.yml b/.github/workflows/shared.twitposter.deploy.yml
--- a/.github/workflows/shared.twitposter.deploy.yml
+++ b/.github/workflows/shared.twitposter.deploy.yml
@@ -24,6 +24,8 @@ permissions:
 
 jobs:
   deploy:
+    outputs:
+      TWITPOSTER_URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     runs-on: ubuntu-latest
     environment:
       name: ${{ inputs.environment }}
@@ -44,3 +46,33 @@ jobs:
         env:
           WEBHOOK_URL: ${{ secrets.AZURE_WEBHOOK_URL_TWITPOSTER }}
         shell: bashraform@v3
+  
+  confirm_deployment:
+    needs: deploy
+    runs-on: ubuntu-latest
+    environment:
+      name: ${{ inputs.environment }}
+    
+    steps:
+      - name: Check Deployment Health
+        id: check-health
+        run: |
+          TWITPOSTER_URL="${{ needs.deploy.outputs.TWITPOSTER_URL }}"
+          IMAGE_TAG="${{ inputs.twitposter_image }}"
+          
+          for i in {1..30}; do
+            echo "Checking health of the deployed application... Attempt $i"
+            response=$(curl -s $TWITPOSTER_URL/health)
+            if echo "$response" | jq -e ".imageTag == \"$IMAGE_TAG\"" > /dev/null; then
+              echo "Deployment verification succeeded: imageTag matches."
+              exit 0
+            fi
+            echo "Deployment verification failed: imageTag does not match. Retrying in 10 seconds..."
+            sleep 10
+          done
+          
+          echo "Deployment verification failed: imageTag did not match after 30 attempts."
+          exit 1
+        shell: bash
+        
+        
